"use server";

import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { sendInvitationEmail } from "@/lib/mailer";

// ─── Types ────────────────────────────────────────────────────────────────────

type ActionState = { error?: string; success?: string } | null;

// ─── Send Invitation ──────────────────────────────────────────────────────────

export async function sendInvitationAction(
  _prevState: ActionState,
  formData: FormData
): Promise<ActionState> {
  const session = await auth();
  if (!session?.user?.id) return { error: "Unauthorized" };

  const workspaceSlug = formData.get("workspaceSlug") as string;
  const email = (formData.get("email") as string)?.trim().toLowerCase();
  const role = formData.get("role") as "ADMIN" | "MEMBER";

  if (!email) return { error: "Email is required." };
  if (!["ADMIN", "MEMBER"].includes(role)) return { error: "Invalid role." };

  // Verify the current user is an admin
  const currentMembership = await prisma.workspaceMember.findFirst({
    where: {
      userId: session.user.id,
      workspace: { slug: workspaceSlug },
    },
    include: { workspace: true, user: true },
  });

  if (currentMembership?.role !== "ADMIN") {
    return { error: "Only admins can send invitations." };
  }

  const workspace = currentMembership.workspace;

  // Check if the user is already a member
  const existingUser = await prisma.user.findUnique({ where: { email } });
  if (existingUser) {
    const alreadyMember = await prisma.workspaceMember.findUnique({
      where: { userId_workspaceId: { userId: existingUser.id, workspaceId: workspace.id } },
    });
    if (alreadyMember) {
      return { error: "This person is already a member of the workspace." };
    }
  }

  // Revoke any previous pending invitations for this email in this workspace
  await prisma.workspaceInvitation.deleteMany({
    where: { email, workspaceId: workspace.id, acceptedAt: null },
  });

  // Create a fresh invitation (7-day expiry, unique token auto-generated by Prisma)
  const invitation = await prisma.workspaceInvitation.create({
    data: {
      email,
      role,
      workspaceId: workspace.id,
      invitedById: session.user.id,
      expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    },
  });

  const baseUrl = process.env.NEXTAUTH_URL ?? "http://localhost:3000";
  const inviteUrl = `${baseUrl}/invite/${invitation.token}`;

  try {
    await sendInvitationEmail({
      toEmail: email,
      workspaceName: workspace.name,
      inviterName: currentMembership.user.name ?? session.user.email ?? "A teammate",
      role,
      inviteUrl,
    });
  } catch (err) {
    // Roll back the invitation row so it can be retried
    await prisma.workspaceInvitation.delete({ where: { id: invitation.id } });
    console.error("[sendInvitationAction] Email send failed:", err);
    return { error: "Failed to send invitation email. Please check your SMTP settings." };
  }

  revalidatePath(`/dashboard/${workspaceSlug}/team`);
  return { success: `Invitation sent to ${email}!` };
}

// ─── Revoke Invitation ────────────────────────────────────────────────────────

export async function revokeInvitationAction(
  _prevState: ActionState,
  formData: FormData
): Promise<ActionState> {
  const session = await auth();
  if (!session?.user?.id) return { error: "Unauthorized" };

  const invitationId = formData.get("invitationId") as string;
  const workspaceSlug = formData.get("workspaceSlug") as string;

  const currentMembership = await prisma.workspaceMember.findFirst({
    where: {
      userId: session.user.id,
      workspace: { slug: workspaceSlug },
    },
  });

  if (currentMembership?.role !== "ADMIN") {
    return { error: "Only admins can revoke invitations." };
  }

  await prisma.workspaceInvitation.deleteMany({
    where: { id: invitationId, workspaceId: currentMembership.workspaceId },
  });

  revalidatePath(`/dashboard/${workspaceSlug}/team`);
  return { success: "Invitation revoked." };
}

// ─── Remove Member (unchanged) ────────────────────────────────────────────────

export async function removeMemberAction(memberId: string, workspaceSlug: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const currentUserMembership = await prisma.workspaceMember.findFirst({
    where: {
      userId: session.user.id,
      workspace: { slug: workspaceSlug },
    },
  });

  if (currentUserMembership?.role !== "ADMIN") {
    throw new Error("Only admins can remove members.");
  }

  if (currentUserMembership.id === memberId) {
    throw new Error(
      "You cannot remove yourself through this dashboard. Please contact support."
    );
  }

  await prisma.workspaceMember.delete({
    where: {
      id: memberId,
      workspaceId: currentUserMembership.workspaceId,
    },
  });

  revalidatePath(`/dashboard/${workspaceSlug}/team`);
}
